# Generated by Django 4.0.3 on 2023-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('passcode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hours', models.FloatField()),
                ('boolean', models.BooleanField()),
            ],
        ),
    ]
