# Generated by Django 4.0.3 on 2023-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('passcode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=100)),
                ('number_of_palyers', models.IntegerField()),
                ('check_in_time', models.CharField(max_length=100)),
                ('check_out_time', models.CharField(default='NA', max_length=100)),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
