# Generated by Django 4.0.3 on 2023-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
