# Generated by Django 4.0.3 on 2023-04-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_playerstatus_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICICIB50_investment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('investment_amount_added', models.IntegerField()),
                ('net_investment', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ICICIB50_profit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profit_amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NASDAQ100_investment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('investment_amount_added', models.IntegerField()),
                ('net_investment', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NASDAQ100_profit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profit_amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerStatus',
        ),
    ]
