# Generated by Django 4.0.3 on 2023-04-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_icicib50_investment_icicib50_profit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ICICIB50_investment',
            new_name='ICICIB22_investment',
        ),
        migrations.RenameModel(
            old_name='ICICIB50_profit',
            new_name='ICICIB22_profit',
        ),
    ]
