# Generated by Django 4.0.3 on 2023-04-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_icicib22_investment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='icicib22_investment',
            table='II',
        ),
        migrations.AlterModelTable(
            name='icicib22_profit',
            table='IP',
        ),
        migrations.AlterModelTable(
            name='nasdaq100_investment',
            table='NI',
        ),
        migrations.AlterModelTable(
            name='nasdaq100_profit',
            table='NP',
        ),
    ]
