# Generated by Django 4.0.3 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_icicib22_investment_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBC_investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount_added', models.IntegerField()),
                ('net_investment', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SI',
            },
        ),
        migrations.CreateModel(
            name='SBC_profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SP',
            },
        ),
    ]
