# Generated by Django 4.0.3 on 2023-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_sbc_investment_sbc_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='icicib22_investment',
            name='avg_share_price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='nasdaq100_investment',
            name='avg_share_price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sbc_investment',
            name='avg_share_price',
            field=models.FloatField(default=1.0),
        ),
    ]
