# Generated by Django 4.0.3 on 2023-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_icicib22_investment_avg_share_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icicib22_investment',
            name='stocks_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icicib22_profit',
            name='stocks_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nasdaq100_investment',
            name='stocks_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nasdaq100_profit',
            name='stocks_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sbc_investment',
            name='stocks_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sbc_profit',
            name='stocks_sold',
            field=models.IntegerField(default=0),
        ),
    ]
