# Generated by Django 4.0.3 on 2023-04-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_icicib22_investment_stocks_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icicib22_investment',
            name='net_investment',
        ),
        migrations.RemoveField(
            model_name='nasdaq100_investment',
            name='net_investment',
        ),
        migrations.RemoveField(
            model_name='sbc_investment',
            name='net_investment',
        ),
    ]
